In [2]:
import pandas as pd
import ast

area_field_1 = pd.read_csv("../csv/hocs/lf_area_data1.csv", index_col=None)
area_field_2 = pd.read_csv("../csv/hocs/lf_area_data2.csv", index_col=None)
area_field_3 = pd.read_csv("../csv/hocs/lf_area_data3.csv", index_col=None)
area_field = pd.concat([area_field_1, area_field_2, area_field_3])
area_field = area_field.reset_index(drop=True)

In [35]:
area_field.to_csv('../csv/hocs/field_train_test/area_field_df_compiled.csv', index=False)

In [3]:
area_field

hist_values            plant
0     [3, 2, 2, 2, 3, 0, 3, 8, 5, 6, 11, 14, 15, 7, ...   acer_campestre
1     [2, 2, 5, 4, 8, 5, 7, 8, 5, 5, 11, 31, 38, 52,...   acer_campestre
2     [13, 14, 24, 12, 14, 14, 18, 13, 25, 47, 54, 4...   acer_campestre
3     [1, 4, 8, 2, 7, 3, 5, 13, 17, 48, 54, 43, 30, ...   acer_campestre
4     [3, 1, 3, 4, 3, 2, 4, 5, 5, 7, 11, 24, 19, 20,...   acer_campestre
...                                                 ...              ...
7085  [5, 5, 7, 1, 1, 0, 1, 1, 7, 9, 23, 37, 32, 21,...  zelkova_serrata
7086  [2, 1, 0, 0, 5, 3, 3, 8, 26, 35, 38, 39, 24, 1...  zelkova_serrata
7087  [5, 0, 0, 0, 0, 4, 6, 10, 11, 11, 37, 52, 34, ...  zelkova_serrata
7088  [3, 2, 1, 0, 1, 3, 5, 10, 26, 33, 37, 48, 35, ...  zelkova_serrata
7089  [2, 1, 1, 0, 0, 1, 0, 4, 5, 10, 20, 25, 51, 44...  zelkova_serrata

[7090 rows x 2 columns]

In [4]:
counts_b = area_field['plant'].value_counts()
print(counts_b.to_string())

prunus_virginiana               183
prunus_sargentii                168
ulmus_pumila                    145
cryptomeria_japonica            122
styrax_japonica                 108
quercus_muehlenbergii           106
aesculus_pavi                   101
acer_palmatum                    92
juglans_cinerea                  91
fraxinus_nigra                   85
salix_nigra                      77
tilia_cordata                    77
carya_glabra                     77
koelreuteria_paniculata          74
catalpa_speciosa                 72
eucommia_ulmoides                71
juniperus_virginiana             65
zelkova_serrata                  63
magnolia_denudata                60
taxodium_distichum               60
pinus_cembra                     59
magnolia_virginiana              58
ulmus_glabra                     56
quercus_marilandica              55
pinus_bungeana                   54
broussonettia_papyrifera         54
malus_pumila                     53
metasequoia_glyptostroboides

In [5]:
area_field_copy = area_field.copy()

for index,row in area_field_copy.iterrows():
    if len(ast.literal_eval(area_field_copy['hist_values'][index])) != 525:
        area_field_copy.drop([index], inplace = True)

KeyboardInterrupt: 

In [ ]:
area_field_copy = area_field_copy.reset_index(drop=True)
area_field_copy

NameError: name 'area_field_copy' is not defined

In [ ]:
area_field_copy_df_train_arr = pd.DataFrame(columns = ['hist_values', 'plant'])
area_field_copy_df_test_arr = pd.DataFrame(columns = ['hist_values', 'plant'])

In [7]:
# from sympy.abc import y
from sklearn.model_selection import train_test_split

for count,value in enumerate(area_field_copy['plant'].unique()):
    # will contain the current plant data
    plant_dictionary ={'hist_values':[], 'plant':[]}

    for index,col in area_field_copy.iterrows():
        # if area_field_copy['plant'][index] == plant:
        plant_dictionary['hist_values'].append(area_field_copy['hist_values'][index])
        plant_dictionary['plant'].append(area_field_copy['plant'][index])
    
    X_train, X_test, y_train, y_test = train_test_split(plant_dictionary['hist_values'], plant_dictionary['plant'], test_size=0.2, random_state=42)

    area_field_copy_df_train_arr['hist_values'] = X_train
    area_field_copy_df_train_arr['plant'] = y_train

    area_field_copy_df_test_arr['hist_values'] = X_test
    area_field_copy_df_test_arr['plant'] = y_test 

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject


In [8]:
area_field_copy_df_train_arr

hist_values               plant
0     [2, 1, 3, 2, 2, 2, 8, 27, 60, 69, 42, 20, 4, 5...   ptelea_trifoliata
1     [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 7, 7, 14, 40, 7...   magnolia_denudata
2     [2, 3, 1, 2, 2, 1, 1, 2, 1, 0, 0, 2, 1, 0, 5, ...    salix_babylonica
3     [1, 1, 3, 4, 14, 14, 11, 18, 18, 21, 21, 18, 1...    pyrus_calleryana
4     [11, 9, 8, 6, 6, 8, 8, 19, 39, 123, 111, 50, 1...    evodia_daniellii
...                                                 ...                 ...
5667  [7, 9, 8, 17, 23, 30, 29, 46, 50, 51, 69, 66, ...        pinus_cembra
5668  [1, 1, 1, 2, 4, 0, 0, 1, 3, 3, 15, 26, 42, 43,...    pyrus_calleryana
5669  [13, 10, 4, 2, 1, 0, 0, 2, 1, 3, 1, 3, 0, 5, 1...  quercus_acutissima
5670  [9, 6, 5, 2, 13, 14, 13, 29, 37, 50, 40, 40, 3...  quercus_macrocarpa
5671  [1, 1, 1, 1, 1, 0, 2, 0, 3, 7, 10, 12, 33, 37,...  betula_populifolia

[5672 rows x 2 columns]

In [9]:
area_field_copy_df_test_arr

hist_values  \
0     [19, 26, 28, 34, 41, 43, 54, 79, 59, 91, 91, 6...   
1     [1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 4, 6, 19,...   
2     [2, 0, 2, 1, 1, 1, 4, 5, 14, 21, 25, 26, 23, 3...   
3     [1, 1, 0, 2, 0, 3, 4, 2, 6, 22, 26, 29, 31, 37...   
4     [5, 14, 12, 12, 15, 26, 35, 49, 58, 43, 28, 20...   
...                                                 ...   
1413  [6, 4, 4, 6, 6, 7, 25, 53, 68, 82, 60, 50, 46,...   
1414  [7, 7, 6, 8, 8, 18, 29, 44, 64, 67, 90, 64, 44...   
1415  [4, 1, 2, 1, 3, 4, 13, 67, 106, 58, 4, 0, 0, 0...   
1416  [1, 11, 2, 0, 3, 9, 6, 17, 24, 24, 38, 44, 61,...   
1417  [2, 0, 5, 2, 2, 1, 3, 2, 0, 0, 0, 4, 6, 0, 7, ...   

                        plant  
0     koelreuteria_paniculata  
1         oxydendrum_arboreum  
2          amelanchier_laevis  
3            carpinus_betulus  
4                 ulmus_rubra  
...                       ...  
1413    betula_alleghaniensis  
1414          corylus_colurna  
1415        magnolia_denudata  
1416       quercus_macrocarpa  
1417          salix_matsudana  

[1418 rows x 2 columns]

In [10]:
print(len(area_field_copy_df_train_arr['plant'].unique()))
print(len(area_field_copy_df_test_arr['plant'].unique()))

173
172


In [11]:
area_field_copy_df_test_arr_2 = area_field_copy_df_test_arr.copy()
novel_dict = {}

for index, row in area_field_copy_df_test_arr_2.iterrows():
    if row['plant'] not in area_field_copy_df_train_arr['plant'].unique():
        novel_dict[row['plant']] = row['hist_values']
        area_field_copy_df_test_arr_2.drop([index], inplace = True)

area_field_copy_df_test_arr = area_field_copy_df_test_arr_2

In [12]:
for field in area_field_copy_df_test_arr['plant'].unique():
    if field in area_field_copy_df_train_arr['plant'].unique():
        print(f"{field} is present in train data")
    else:
        print(f"{field} is not present in train data")

koelreuteria_paniculata is present in train data
oxydendrum_arboreum is present in train data
amelanchier_laevis is present in train data
carpinus_betulus is present in train data
ulmus_rubra is present in train data
styrax_japonica is present in train data
aesculus_flava is present in train data
quercus_montana is present in train data
cryptomeria_japonica is present in train data
ulmus_parvifolia is present in train data
betula_alleghaniensis is present in train data
gleditsia_triacanthos is present in train data
malus_floribunda is present in train data
magnolia_tripetala is present in train data
pinus_flexilis is present in train data
metasequoia_glyptostroboides is present in train data
ulmus_glabra is present in train data
asimina_triloba is present in train data
quercus_muehlenbergii is present in train data
crataegus_phaenopyrum is present in train data
corylus_colurna is present in train data
chamaecyparis_thyoides is present in train data
prunus_sargentii is present in train 

In [13]:
import pandas as pd
import ast

In [14]:
area_field_copy_df_train_arr.to_csv('../csv/hocs/field_train_test/area_field_df_train.csv', index=False)
area_field_copy_df_test_arr.to_csv('../csv/hocs/field_train_test/area_field_df_test.csv', index=False)

In [6]:
area_field_copy_df_train_arr = pd.read_csv('../csv/hocs/field_train_test/area_field_df_train.csv')
area_field_copy_df_test_arr = pd.read_csv('../csv/hocs/field_train_test/area_field_df_test.csv')

# NEAREST NEIGHBORS

In [7]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

import pandas as pd
import numpy as np

In [8]:
from sklearn.preprocessing import LabelEncoder

categories_train = area_field_copy_df_train_arr['plant']
# Initialize the LabelEncoder
le_train = LabelEncoder()
# Fit the LabelEncoder to the categories
le_train.fit(categories_train)
# Transform the categories into integer labels
species_labels_train = le_train.transform(categories_train)

categories_test = area_field_copy_df_test_arr['plant']
species_labels_test = le_train.transform(categories_test)

In [9]:
species_labels_train

array([128,  76, 151, ..., 130, 136,  25])

In [10]:
species_labels_test

array([ 71,  94,  19, ...,  76, 136, 153])

In [11]:
for test in species_labels_test:
    if test in species_labels_train:
        print(f"{test} is present in lab")
    else:
        print(f"{test} is not present in lab")

71 is present in lab
94 is present in lab
19 is present in lab
27 is present in lab
171 is present in lab
158 is present in lab
11 is present in lab
158 is present in lab
139 is present in lab
54 is present in lab
169 is present in lab
21 is present in lab
64 is present in lab
86 is present in lab
81 is present in lab
101 is present in lab
89 is present in lab
168 is present in lab
20 is present in lab
20 is present in lab
140 is present in lab
51 is present in lab
48 is present in lab
41 is present in lab
121 is present in lab
104 is present in lab
88 is present in lab
68 is present in lab
141 is present in lab
88 is present in lab
158 is present in lab
62 is present in lab
71 is present in lab
152 is present in lab
47 is present in lab
65 is present in lab
117 is present in lab
24 is present in lab
158 is present in lab
30 is present in lab
94 is present in lab
40 is present in lab
71 is present in lab
118 is present in lab
79 is present in lab
37 is present in lab
54 is present in l

In [12]:
hv_train = [ast.literal_eval(d) for d in area_field_copy_df_train_arr['hist_values']]
hv_test = [ast.literal_eval(d) for d in area_field_copy_df_test_arr['hist_values']]

In [13]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

# # Load the features extracted from the database of lab and field images
# database_features = np.load("path/to/database_features.npy")

# Create a nearest neighbors object with n_neighbors set to 25
nbrs = NearestNeighbors(n_neighbors=25, algorithm='auto').fit(hv_train)
nbrs

NearestNeighbors(n_neighbors=25)

In [14]:
input_hist = np.array([8, 16, 17, 13, 16, 10, 6, 10, 7, 11, 49, 101, 78, 13, 10, 3, 3, 4, 1, 1, 4, 14, 24, 23, 18, 7, 13, 12, 10, 8, 8, 62, 103, 28, 12, 13, 9, 5, 6, 0, 2, 4, 17, 31, 27, 13, 16, 15, 9, 7, 15, 19, 62, 63, 18, 20, 14, 10, 11, 5, 3, 2, 4, 18, 37, 24, 19, 16, 12, 8, 20, 20, 20, 41, 44, 19, 16, 17, 13, 14, 10, 6, 3, 4, 17, 39, 24, 20, 16, 13, 18, 18, 22, 21, 23, 25, 21, 18, 15, 14, 15, 14, 15, 10, 3, 15, 40, 27, 18, 19, 15, 23, 22, 20, 15, 20, 18, 20, 13, 16, 21, 12, 11, 12, 18, 6, 17, 35, 31, 15, 23, 26, 21, 18, 19, 14, 19, 18, 17, 12, 23, 17, 11, 16, 10, 10, 9, 14, 33, 31, 23, 20, 23, 29, 14, 17, 11, 22, 15, 22, 18, 19, 11, 18, 13, 7, 8, 13, 8, 33, 34, 25, 20, 19, 29, 17, 16, 12, 22, 16, 25, 17, 20, 12, 17, 11, 5, 9, 14, 7, 33, 31, 29, 20, 17, 22, 24, 15, 15, 21, 17, 26, 16, 11, 18, 8, 18, 10, 10, 13, 24, 30, 26, 20, 19, 15, 14, 30, 18, 16, 20, 20, 17, 17, 15, 12, 14, 19, 9, 11, 15, 28, 24, 18, 19, 17, 17, 19, 22, 24, 18, 17, 20, 17, 14, 15, 15, 14, 21, 15, 12, 15, 22, 18, 15, 19, 17, 19, 17, 25, 20, 19, 20, 19, 17, 12, 16, 16, 21, 20, 21, 9, 19, 12, 18, 13, 12, 22, 22, 15, 21, 18, 23, 20, 16, 23, 13, 18, 18, 15, 25, 21, 16, 20, 8, 12, 16, 15, 15, 26, 15, 18, 14, 20, 25, 13, 18, 26, 14, 19, 20, 20, 24, 22, 21, 8, 9, 17, 17, 19, 18, 14, 14, 17, 13, 23, 19, 16, 22, 22, 17, 20, 24, 23, 24, 25, 5, 12, 15, 18, 17, 16, 10, 16, 12, 15, 16, 24, 19, 17, 26, 16, 20, 22, 25, 31, 29, 12, 12, 11, 14, 20, 12, 7, 15, 11, 15, 13, 26, 21, 16, 23, 18, 17, 23, 26, 34, 35, 6, 8, 12, 12, 15, 15, 12, 9, 14, 10, 17, 17, 22, 20, 17, 23, 21, 21, 29, 35, 46, 4, 4, 7, 9, 15, 12, 16, 9, 13, 17, 13, 17, 16, 20, 17, 17, 27, 21, 30, 37, 60, 4, 3, 3, 6, 9, 13, 15, 14, 14, 12, 14, 18, 15, 13, 19, 20, 17, 31, 27, 37, 77, 3, 3, 2, 3, 5, 11, 16, 18, 13, 10, 11, 16, 14, 18, 13, 20, 18, 23, 30, 39, 95, 2, 4, 1, 2, 5, 12, 12, 14, 14, 11, 10, 8, 17, 14, 18, 12, 24, 18, 32, 38, 113, 2, 2, 2, 3, 8, 11, 9, 10, 10, 12, 10, 10, 7, 18, 14, 17, 14, 24, 23, 41, 134, 2, 2, 3, 7, 9, 7, 7, 7, 8, 11, 9, 10, 7, 13, 13, 15, 19, 18, 24, 41, 149])
print(len(input_hist))

525


In [23]:
# Use the HoCS feature vector extracted from the input image as the query
query = input_hist.reshape(1, -1)

In [24]:
# Perform the nearest neighbors search
distances, indices = nbrs.kneighbors(query)

In [25]:
distances

array([[123.4503949 , 177.79763778, 183.17477992, 186.47788073,
        198.56233278, 205.24862972, 208.11535263, 209.68070965,
        213.45257084, 214.14714567, 218.55434107, 220.69662435,
        223.73421732, 223.74315632, 225.82736769, 227.78059619,
        229.88475374, 231.19472312, 231.66139083, 233.71991785,
        234.56342426, 234.69554747, 235.40390821, 241.09334292,
        243.06172056]])

In [26]:
indices

array([[3384, 1949, 4403, 1151,  280, 5213, 2600, 2918, 2333,  616, 1194,
         532, 4741,  624,  135, 3089, 5379,   56, 5609, 3088, 1871, 2059,
        3785,  966, 5045]], dtype=int64)

In [27]:
import matplotlib.pyplot as plt
from PIL import Image

# Show the top 25 matches to the user
for i in range(len(indices[0])):
    index = indices[0][i]
    distance = distances[0][i]
    species = species_labels_train[index]
    # image_path = "../../leafsnap/leafsnap-dataset/dataset/1img_compiled/" + str(index) + ".jpg" # Assuming the images are named as their corresponding index in the database

    # # Load and show the matched image
    # img = Image.open(image_path)
    # plt.imshow(img)
    # plt.show()

    # Print the match information
    print(f"Match {i+1} Species: {area_field_copy_df_train_arr['plant'][index]} Distance: {distance}")
# Assuming that you have already loaded the database of features and the list of species labels
# as numpy arrays called database_features and species_labels, respectively

Match 1 Species: liquidambar_styraciflua Distance: 123.45039489608772
Match 2 Species: liquidambar_styraciflua Distance: 177.79763777958357
Match 3 Species: liquidambar_styraciflua Distance: 183.17477992343814
Match 4 Species: liquidambar_styraciflua Distance: 186.47788072583836
Match 5 Species: liquidambar_styraciflua Distance: 198.5623327824288
Match 6 Species: aesculus_pavi Distance: 205.24862971527972
Match 7 Species: carya_glabra Distance: 208.11535262925702
Match 8 Species: liquidambar_styraciflua Distance: 209.6807096516034
Match 9 Species: carya_tomentosa Distance: 213.45257084420416
Match 10 Species: carya_tomentosa Distance: 214.14714567324964
Match 11 Species: ptelea_trifoliata Distance: 218.5543410687603
Match 12 Species: carya_tomentosa Distance: 220.69662435116672
Match 13 Species: liquidambar_styraciflua Distance: 223.73421732046262
Match 14 Species: liquidambar_styraciflua Distance: 223.74315631991965
Match 15 Species: liquidambar_styraciflua Distance: 225.8273676948832

In [28]:
indices[0]

array([3384, 1949, 4403, 1151,  280, 5213, 2600, 2918, 2333,  616, 1194,
        532, 4741,  624,  135, 3089, 5379,   56, 5609, 3088, 1871, 2059,
       3785,  966, 5045], dtype=int64)

In [20]:
from sklearn.model_selection import LeaveOneOut

# Perform leave-one-image-out species identification using only the field images as queries
loo = LeaveOneOut()
correct_ranks = []

for index,test_index in enumerate(hv_test):
    # Only use field images as queries
    # if "field" not in image_paths[test_index[0]]:
    #     continue
    # Extract the HoCS feature vector from the query image
    query = test_index
    query = np.array(query)
    # Perform the nearest neighbors search
    distances, indices = nbrs.kneighbors(query.reshape(1, -1))
    # Get the species labels of the matches
    match_species = species_labels_train[indices[0]]
    # Get the true species label of the query image
    true_species = species_labels_test[index]
    
    if (len(np.where(match_species == true_species)[0])) != 0:
        rank = np.where(match_species == true_species)[0] + 1

    print(rank)
    correct_ranks.append(rank)


[10]
[5]
[5]
[5]
[1 4 9]
[ 7 21]
[ 7 21]
[10 14 16]
[ 1  2 12 15 16 17 20 21]
[ 1  3  4  5  6  7  8  9 11 22 23]
[22]
[22]
[ 6  8 13]
[ 1  2  4  7 19]
[3]
[ 1  9 11]
[ 1  9 11]
[7 8]
[ 1  6 14 22]
[ 2  8 15]
[ 5  6  9 10]
[ 5  6  9 10]
[ 1 22]
[ 7 20]
[ 2  3 13 17]
[ 1  4  9 12 17]
[ 1  4  9 12 17]
[2]
[ 7 25]
[ 1  6  7 13 25]
[18 20 23]
[1]
[1]
[16]
[16]
[ 1  3  4  5  6  9 11 12 14 15]
[ 2  3 11 19 22]
[1]
[1 2 4 5]
[ 1  2  4  5  7  8  9 11 13 15 16 18 20 25]
[ 7 17]
[ 2 19]
[ 1  2  3  4  5  6 12 14 15 16 19 25]
[ 1  2  3  4  5  6 12 14 15 16 19 25]
[ 1  2  3  4  5  6 12 14 15 16 19 25]
[21]
[ 6  7 14 15 17 18 19]
[10]
[5 6]
[5 6]
[ 1  2  5  9 10 15 20 22]
[ 1  2  5  9 10 15 20 22]
[ 1  2  5  9 10 15 20 22]
[ 1 20]
[ 1 12 15 19 23 24]
[ 1 12 15 19 23 24]
[ 1 12 15 19 23 24]
[ 1 12 15 19 23 24]
[ 1 12 15 19 23 24]
[11]
[13 22 24]
[13 22 24]
[13 22 24]
[23]
[8]
[8]
[ 6 10]
[ 6 10]
[ 6 10]
[ 5  8 12]
[ 5  8 12]
[ 1  3  5  8  9 18 19]
[ 2  5  7 16 17 18]
[ 1  2  4  5  8 10 11 12 14 17 19 

In [25]:
correct_ranks

[array([10], dtype=int64),
 array([5], dtype=int64),
 array([5], dtype=int64),
 array([5], dtype=int64),
 array([1, 4, 9], dtype=int64),
 array([ 7, 21], dtype=int64),
 array([ 7, 21], dtype=int64),
 array([10, 14, 16], dtype=int64),
 array([ 1,  2, 12, 15, 16, 17, 20, 21], dtype=int64),
 array([ 1,  3,  4,  5,  6,  7,  8,  9, 11, 22, 23], dtype=int64),
 array([22], dtype=int64),
 array([22], dtype=int64),
 array([ 6,  8, 13], dtype=int64),
 array([ 1,  2,  4,  7, 19], dtype=int64),
 array([3], dtype=int64),
 array([ 1,  9, 11], dtype=int64),
 array([ 1,  9, 11], dtype=int64),
 array([7, 8], dtype=int64),
 array([ 1,  6, 14, 22], dtype=int64),
 array([ 2,  8, 15], dtype=int64),
 array([ 5,  6,  9, 10], dtype=int64),
 array([ 5,  6,  9, 10], dtype=int64),
 array([ 1, 22], dtype=int64),
 array([ 7, 20], dtype=int64),
 array([ 2,  3, 13, 17], dtype=int64),
 array([ 1,  4,  9, 12, 17], dtype=int64),
 array([ 1,  4,  9, 12, 17], dtype=int64),
 array([2], dtype=int64),
 array([ 7, 25], dtype

In [24]:
# Calculate the recognition rate as a function of the maximum species match rank
recognition_rates = []
for i in range(1, 26):
    recognition_rate = sum([1 for rank in correct_ranks if rank <= i]) / len(correct_ranks)
    recognition_rates.append(recognition_rate)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [23]:
recognition_rates

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092,
 0.0007052186177715092]